In [1]:
import numpy as np

In [3]:
"""
ndarray.ndim 	秩，即轴的数量或维度的数量
ndarray.shape 	数组的维度，对于矩阵，n 行 m 列
ndarray.size 	数组元素的总个数，相当于 .shape 中 n*m 的值
ndarray.dtype 	ndarray 对象的元素类型
ndarray.itemsize 	ndarray 对象中每个元素的大小，以字节为单位
ndarray.flags 	ndarray 对象的内存信息
ndarray.real 	ndarray元素的实部
ndarray.imag 	ndarray 元素的虚部
ndarray.data 	包含实际数组元素的缓冲区，由于一般通过数组的索引获取元素，所以通常不需要使用这个属性。
"""

'\nndarray.ndim \t秩，即轴的数量或维度的数量\nndarray.shape \t数组的维度，对于矩阵，n 行 m 列\nndarray.size \t数组元素的总个数，相当于 .shape 中 n*m 的值\nndarray.dtype \tndarray 对象的元素类型\nndarray.itemsize \tndarray 对象中每个元素的大小，以字节为单位\nndarray.flags \tndarray 对象的内存信息\nndarray.real \tndarray元素的实部\nndarray.imag \tndarray 元素的虚部\nndarray.data \t包含实际数组元素的缓冲区，由于一般通过数组的索引获取元素，所以通常不需要使用这个属性。\n'

In [18]:
## 数组的秩
a = np.arange(24)
print(a)
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)
print(a.itemsize)
print(a.flags)
print(a.real)
print(a.imag)
print(a.data)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
1
(24,)
24
int32
4
  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [19]:
## ndarray.reshape 通常返回的是非拷贝副本，即改变返回后数组的元素，原数组对应元素的值也会改变。
print(a.reshape)

<built-in method reshape of numpy.ndarray object at 0x000001357F1CB300>
