In [7]:
import tensorflow as tf
from tensorflow.keras import layers
model = tf.keras.Sequential()
model.add(layers.Dense(32, activation='relu'))
model.add(layers.Dense(32, activation='relu'))
model.add(layers.Dense(10, activation='softmax'))

In [8]:
layers.Dense(32, activation='sigmoid')
layers.Dense(32, activation=tf.sigmoid)
layers.Dense(32, kernel_initializer='orthogonal')
layers.Dense(32, kernel_initializer=tf.keras.initializers.glorot_normal)
layers.Dense(32, kernel_regularizer=tf.keras.regularizers.l2(0.01))
layers.Dense(32, kernel_regularizer=tf.keras.regularizers.l1(0.01))

In [9]:
model = tf.keras.Sequential()
model.add(layers.Dense(32, activation='relu'))
model.add(layers.Dense(32, activation='relu'))
model.add(layers.Dense(10, activation='softmax'))
model.compile(optimizer=tf.keras.optimizers.Adam(0.001),
             loss=tf.keras.losses.categorical_crossentropy,
             metrics=[tf.keras.metrics.categorical_accuracy])

In [10]:
import numpy as np

train_x = np.random.random((1000, 72))
train_y = np.random.random((1000, 10))

val_x = np.random.random((200, 72))
val_y = np.random.random((200, 10))

model.fit(train_x, train_y, epochs=10, batch_size=100,
          validation_data=(val_x, val_y))

Epoch 1/10
10/10 [==============================] - 0s 20ms/step - loss: 11.8313 - categorical_accuracy: 0.0950 - val_loss: 11.9468 - val_categorical_accuracy: 0.1150
Epoch 2/10
10/10 [==============================] - 0s 3ms/step - loss: 12.2787 - categorical_accuracy: 0.0920 - val_loss: 12.6372 - val_categorical_accuracy: 0.1150
Epoch 3/10
10/10 [==============================] - 0s 3ms/step - loss: 13.4763 - categorical_accuracy: 0.0920 - val_loss: 14.3738 - val_categorical_accuracy: 0.1150
Epoch 4/10
10/10 [==============================] - 0s 4ms/step - loss: 16.0555 - categorical_accuracy: 0.0920 - val_loss: 17.3849 - val_categorical_accuracy: 0.1150
Epoch 5/10
10/10 [==============================] - 0s 3ms/step - loss: 19.0261 - categorical_accuracy: 0.0920 - val_loss: 19.7979 - val_categorical_accuracy: 0.1150
Epoch 6/10
10/10 [==============================] - 0s 3ms/step - loss: 20.9441 - categorical_accuracy: 0.0920 - val_loss: 20.9439 - val_categorical_accuracy: 0.1150
Epo

In [11]:
dataset = tf.data.Dataset.from_tensor_slices((train_x, train_y))
dataset = dataset.batch(32)
dataset = dataset.repeat()
val_dataset = tf.data.Dataset.from_tensor_slices((val_x, val_y))
val_dataset = val_dataset.batch(32)
val_dataset = val_dataset.repeat()

model.fit(dataset, epochs=10, steps_per_epoch=30,
          validation_data=val_dataset, validation_steps=3)

Epoch 1/10

If you intended to run this layer in float32, you can safely ignore this warning. If in doubt, this warning is likely only an issue if you are porting a TensorFlow 1.X model to TensorFlow 2.

To change all layers to have dtype float64 by default, call `tf.keras.backend.set_floatx('float64')`. To change just this layer, pass dtype='float64' to the layer constructor. If you are the author of this layer, you can disable autocasting by passing autocast=False to the base Layer constructor.

30/30 [==============================] - 0s 6ms/step - loss: 56.6079 - categorical_accuracy: 0.1135 - val_loss: 68.4604 - val_categorical_accuracy: 0.1354
Epoch 2/10
30/30 [==============================] - 0s 2ms/step - loss: 91.0413 - categorical_accuracy: 0.1132 - val_loss: 109.1964 - val_categorical_accuracy: 0.1146
Epoch 3/10
30/30 [==============================] - 0s 2ms/step - loss: 140.7685 - categorical_accuracy: 0.1100 - val_loss: 162.4324 - val_categorical_accuracy: 0.1042
Epoch 4

In [12]:
test_x = np.random.random((1000, 72))
test_y = np.random.random((1000, 10))
model.evaluate(test_x, test_y, batch_size=32)
test_data = tf.data.Dataset.from_tensor_slices((test_x, test_y))
test_data = test_data.batch(32).repeat()
model.evaluate(test_data, steps=30)
# predict
result = model.predict(test_x, batch_size=32)
print(result)

30/30 [==============================] - 0s 2ms/step - loss: 654.4271 - categorical_accuracy: 0.1000
[[0.         0.01090581 0.02755141 ... 0.         0.20169899 0.18266524]
 [0.         0.01292888 0.03528189 ... 0.         0.2561573  0.13684359]
 [0.         0.0081198  0.02209348 ... 0.         0.20178376 0.25858992]
 ...
 [0.         0.01803927 0.02756038 ... 0.         0.27780688 0.09405864]
 [0.         0.00733325 0.01299656 ... 0.         0.31242737 0.12935184]
 [0.         0.01344841 0.02841472 ... 0.         0.29724705 0.12635495]]
